
export const SELECT_CATEGORY = 'SELECT_CATEGORY';
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const ADD_CHILD_CATEGORY = 'ADD_CHILD_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const EDIT_CATEGORY = 'EDIT_CATEGORY';
export const CANCEL_EDIT_CATEGORY = 'EDIT_CATEGORY';
export const RENAME_CATEGORY = 'RENAME_CATEGORY';